---
title: "steel_plant_analysis"
author: "Michael Zargari"
format: html
---

## Reading in Data
```{r}
library(here)
library(tidyverse)

scope_1_and_2_emissions_2021 <- read_csv(here("output-data", "2021_steel_plant_emissions_and_productions.csv"))
```

## Data Analysis

### Regional Analysis

```{r}
total_regional_emissions <- scope_1_and_2_emissions_2021 %>% 
  group_by(region) %>% 
  summarise(total_emissions_co2e = sum(total_co2e_tonnes_2021)) %>% 
  arrange(desc(total_emissions_co2e))
  
average_regional_emissions <- scope_1_and_2_emissions_2021 %>% 
  group_by(region) %>% 
  summarise(avg_emissions_per_region_co2e = mean(total_co2e_tonnes_2021)) %>% 
  arrange(desc(avg_emissions_per_region_co2e))
```

### State-Level Analysis

```{r}
total_state_emissions <- scope_1_and_2_emissions_2021 %>% 
  group_by(state) %>% 
  summarise(total_emissions_co2e = sum(total_co2e_tonnes_2021)) %>% 
  arrange(desc(total_emissions_co2e))
  
average_state_emissions <- scope_1_and_2_emissions_2021 %>% 
  group_by(state) %>% 
  summarise(avg_emissions_per_plant_co2e = mean(total_co2e_tonnes_2021)) %>% 
  arrange(desc(avg_emissions_per_plant_co2e))
```

### Materials Analysis
```{r}
types_of_steel_produced <- scope_1_and_2_emissions_2021 %>% 
  select(c(plant_id, category_steel_product, steel_products, total_co2e_tonnes_2021, total_tonnes_steel_produced_2021)) %>% 
  separate_rows(category_steel_product, sep = "; ")

types_of_steel_produced %>% 
  group_by(category_steel_product) %>% 
  summarise(avg_pollution_at_plant = mean(total_co2e_tonnes_2021))
```
